# https://circleci.com/developer/orbs/orb/circleci/terraform
version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.3
workflows:
  build_images:r
      build:
        machine:
          image: ubuntu-2204:2022.04.2
        steps:
          - run: |
              docker build -f docker/Dockerfile -t enimapod-api .
              


  deploy_infra:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: ./infra/environments/dev
      - terraform/validate:
          checkout: true
          context: terraform
          path: ./infra/environments/dev
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          out: dev.tfplan
          path: ./infra/environments/dev
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: ./infra/environments/dev
          plan: dev.tfplan
          filters:
            branches:
              only: main
          requires:
            - terraform/plan